trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: first_job
    steps:
    - bash: echo Build job - First job
  - job: second_job
    steps:
    - bash: echo Build job - Second job
- stage: Deploy
  jobs:
  - job: first_job
    steps:
    - bash: echo Deploy job - First job
  - job: second_job
    steps:
    - bash: echo Deploy job - Second job    

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
