trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: first_job
    steps:
    - bash: echo Build job - First job
  - job: second_job
    steps:
    - bash: echo Build job - Second job
- stage: Dev
  dependsOn: Build 
  jobs:
  - job: first_job
    steps:
    - bash: echo Deploy job - First job
  - job: second_job
    steps:
    - bash: echo Deploy job - Second job
- stage: QA
  dependsOn: Build
  jobs:
  - job: first_job
    steps:
    - bash: echo Deploy job - First job
  - job: second_job
    steps:
    - bash: echo Deploy job - Second job
- stage: Prod
  dependsOn:
  - Dev
  - QA
  jobs:
  - job: first_job
    steps:
    - bash: echo Deploy job - First job
  - job: second_job
    steps:
    - bash: echo Deploy job - Second job            
