trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  variables:
    stagename: Build_Job
    user: Prasanta
  jobs:
  - job: first_job
    steps:
    - bash: echo Build job - First job
    - bash: echo Build name is $(stagename) and username is $(user)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - bash: echo $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: echo $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        MaxArtifactSize: 10
#   - job: second_job
#     steps:
#     - bash: echo Build job - Second job
# - stage: Dev
#   dependsOn: Build_Job
#   jobs:
#   - job: first_job
#     steps:
#     - bash: echo Deploy job - First job
#   - job: second_job
#     steps:
#     - bash: echo Deploy job - Second job
# - stage: QA
#   dependsOn: Build_Job
#   jobs:
#   - job: first_job
#     steps:
#     - bash: echo Deploy job - First job
#   - job: second_job
#     steps:
#     - bash: echo Deploy job - Second job
# - stage: Prod
#   dependsOn:
#   - Dev
#   - QA
#   jobs:
#   - job: first_job
#     steps:
#     - bash: echo Deploy job - First job
#   - job: second_job
#     steps:
#     - bash: echo Deploy job - Second job            
